### ISSUE TITLE
Invalid protobuf byte sequence

### ISSUE THREAD

**Issue by deppyu** [jnewmano/grpc-json-proxy#1]
hi guy:
   i test my grpc application with postman according to your turorial, but i get "error":"Invalid protobuf byte sequence"   
![_20180813200910](https://user-images.githubusercontent.com/4425280/44030972-02871980-9f35-11e8-9d3e-a716c3439381.png)
![2](https://user-images.githubusercontent.com/4425280/44030977-079dd760-9f35-11e8-8da1-7848fd271555.png)
![3](https://user-images.githubusercontent.com/4425280/44030984-147cf542-9f35-11e8-8e2e-8dc81320f15d.png)

could you help me, please!

**Comment by jnewmano** [comment]
Can you post the proto message for the request and reply?

**Comment by deppyu** [comment]
this is my proto file:

`syntax = "proto3";
option java_multiple_files = true;
option java_package = "com.orientsec.demo";
option java_outer_classname = "GreeterProto";
package com.orientsec.demo;


service Greeter {
    rpc sayHello (GreeterRequest) returns (GreeterReply) {}
}

message GreeterRequest {
    string name = 1;
//    int32  no   = 1;
//    string name = 2;
//    bool sex = 3;
//    double salary = 4;
//    string desc = 5;
}

message GreeterReply {
    bool success = 1;
    string message = 2;
//    int32  no   = 3;
//    double salary = 4;
//    int64 total = 5;
}`

**Comment by deppyu** [comment]
detail error message:

 Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1@7444ca80
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:530)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:173)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:94)
	at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:268)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messageRead(ServerCallImpl.java:266)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1.runInContext(ServerImpl.java:660)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:82)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.skipRawBytes(CodedInputStream.java:1199)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.skipField(CodedInputStream.java:577)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.skipMessage(CodedInputStream.java:649)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.skipField(CodedInputStream.java:580)
	at com.orientsec.demo.GreeterRequest.<init>(GreeterRequest.java:45)
	at com.orientsec.demo.GreeterRequest.<init>(GreeterRequest.java:9)
	at com.orientsec.demo.GreeterRequest$1.parsePartialFrom(GreeterRequest.java:781)
	at com.orientsec.demo.GreeterRequest$1.parsePartialFrom(GreeterRequest.java:776)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parseFrom(ProtoLiteUtils.java:178)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:170)

**Comment by jnewmano** [comment]
The proxy requires that your server have a JSON codec registered in your gRPC server. I don’t have any experience with gRPc and Java so I’m not sure how to do it in Java.
